
- name: update apt
  become: yes
  apt: update_cache=yes

- name: install first-tier support packages
  become: yes
  apt: name={{ item }} state=present force=yes
  with_items:
    - software-properties-common


- name: add gcc-4.9 repository
  become: yes
  shell: add-apt-repository ppa:ubuntu-toolchain-r/test 

- name: update apt
  become: yes
  apt: update_cache=yes

- name: install support packages from apt
  become: yes
  apt: name={{ item }} state=present force=yes
  with_items:
    - gcc-4.9
    - g++-4.9
    - git
    - openexr
    - libeigen3-dev
    - libeigen3-doc
    - mesa-common-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - freeglut3
    - freeglut3-dev
    - binutils-gold
    - libbz2-dev
    - libflann-dev
    - libvtk-java
    - python-vtk
    - libvtk5-dev
    - libvtk5-qt4-dev
    - libvtk5.8
    - libvtk5.8-qt4
    - lvtk-dev
    - openssl
    - libc-ares-dev
    - sqlite3
    - libturbojpeg
    - libsuitesparse-dev
    - libqglviewer-dev
    - libglew-dev

- name: install support packages from deb
  became: yes
  apt: deb={{ item }}
  with_fileglob:
    - roles/support/files/*.deb

- name: unarchive packages build from source
  became: yes
  unarchive: src={{ item }} dest=/
  with_fileglob:
    - roles/support/files/*.tar.gz

- name: copy FindEigen3.cmake
  become: yes
  shell: cp /usr/share/cmake-2.8/Modules/FindEigen3.cmake /usr/local/share/cmake-3.5/Modules/

- name: gcc g++ quick version switch 
  become: yes
  shell: |
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20

- name: link libboost_system libboost_date_time
  become: yes
  shell: |
    ln -s /usr/local/lib/libboost_system.so.1.60.0 /usr/lib/libboost_system.so.1.54.0
    ln -s /usr/local/lib/libboost_date_time.so.1.60.0 /usr/lib/libboost_date_time.so.1.54.0

- name: link libturbojpeg
  become: yes
  shell: ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
